poldyaev.ru
Poldyaich97/poldyaev.ru pull request #1
Opened 2022-04-21 12:34 UTC by Poldyaich97

2022-04-21 19:44 UTC, chervyakovru commented
Визульные проблемы  Header:

- [ ] Выравнивание не вертикали элементов

![image](https://user-images.githubusercontent.com/14909082/164538553-1defb779-1f24-4536-9c04-48fa7ddcf06e.png)

- [ ] Кнопка должна быть полностью наводимой. Т.е. когда переводишь мышку с текста на стрелочку анимация не должна скакать
![image](https://user-images.githubusercontent.com/14909082/164538655-b4da7d47-8516-4b44-bb2c-45a55c0a3efc.png)

- [ ] Выравнивание не вертикали элементов
![image](https://user-images.githubusercontent.com/14909082/164539722-0f66c6ab-3c80-40ca-ac54-4425db580800.png)

- [ ] На макете этот кружок чуть меньше
![image](https://user-images.githubusercontent.com/14909082/164540522-0330d643-86f1-486d-a2cb-ce048371e3bc.png)

2022-04-21 19:51 UTC, chervyakovru commented
Main

- [ ] Расстояние между Header и Main 50px, а не 40
- [ ] Между Main и Footer 90

- [ ] Высота меньше, чем в макете
![image](https://user-images.githubusercontent.com/14909082/164541031-4bf99c9d-012a-45d7-a0b7-3303c8ba0799.png)

- [ ] Не хватает ховера
![image](https://user-images.githubusercontent.com/14909082/164541204-e884fa43-8be6-41c2-9afa-8ea34aa23825.png)

![image](https://user-images.githubusercontent.com/14909082/164541193-b3b4f033-9e5c-426e-9ee5-6bf162c99fb5.png)

2022-04-21 20:05 UTC, chervyakovru commented
Высота на макете 400 - на сайте 357 (потому что цифры в padding местами поменял)
![image](https://user-images.githubusercontent.com/14909082/164541865-6b436f1a-dd1f-4ed9-890b-563744ca5309.png)
- [ ] Расстояние между портфолио и footer 120

- [ ] Ломается ширина контейнера
![image](https://user-images.githubusercontent.com/14909082/164542535-1650582a-4cbe-435f-8514-e563b80ae76f.png)

- [ ] Не хватает емодзи
![image](https://user-images.githubusercontent.com/14909082/164542648-2fb5b574-29d2-4e2a-b172-b87361ab35a0.png)

- [ ] Высота кнопки в 2 раза больше чем в макете
![image](https://user-images.githubusercontent.com/14909082/164542812-c8963bf2-673b-4e1f-8841-60d527c02791.png)

- [ ] Шрифт другой ширины
![image](https://user-images.githubusercontent.com/14909082/164542896-4f44c67d-4aa6-4638-b894-821249b06b5e.png)

- [ ] Че-то тут совсем все куда-то поехало. Должен быть отступ между заголовком и кнопками 80px и между кнопками и нижней линией 180
![image](https://user-images.githubusercontent.com/14909082/164543009-e85b7f87-7ac6-4f05-a8af-2cdcc08e2107.png)

- [ ] Тут и горизонтальное и вертикальное выравнивание оплошали
![image](https://user-images.githubusercontent.com/14909082/164543653-f2ee0c5c-6750-4077-bc83-e1b8932c6302.png)

2022-04-21 20:07 UTC, chervyakovru commented
В консоли варнинг на который стоит обратить внимание и исправить проблему
![image](https://user-images.githubusercontent.com/14909082/164543846-a94d36a7-9a00-4386-a5f9-50a6c1812c1b.png)

2022-04-21 20:09 UTC, chervyakovru commented
Не просто заметить, но в макете добавлен шум. Он там не случайно, его нужно добавить
![image](https://user-images.githubusercontent.com/14909082/164544118-337335a7-0122-45fc-bd85-a5587cbb6c7b.png)

2022-04-21 20:20 UTC, chervyakovru requested changes

2022-04-21 20:20 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +  height: 47px;
padding-ами не решить?

2022-04-21 20:20 UTC, chervyakovru commented on src/App.css
> +  margin: 0;
не нужно

2022-04-21 20:20 UTC, chervyakovru commented on src/App.css
>  .App-logo {
тут остались лишние стили

2022-05-02 21:18 UTC, chervyakovru requested changes

2022-05-02 21:18 UTC, chervyakovru commented on src/App.css
>    display: flex;
Тебе не нужен flex. Блоки и так идут друг под другом

2022-05-02 21:18 UTC, chervyakovru commented on src/App.tsx
> +// import React from "react";
comment

2022-05-02 21:18 UTC, chervyakovru commented on src/App.tsx
> +import "./App.css";
Не нужен

2022-05-02 21:18 UTC, chervyakovru commented on src/App.tsx
>      <div className="App">
className не нужен

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +  min-height: 640px;
почему min-height а не height?

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +  display: flex;
тут не нужен flex. Блочные элементы и так друг под другом идут без отсупов

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +  border: 0.2px solid #ffffff;
браузер не умеет рисовать не целые пиксели. Тут будет 1

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +  border: 1px solid #ffffff;
линию не нужно задавать бордером. в таком случае появляется сайдэффект в виде увеличенной ширины. Лучше сделать height: 1px и background: #fff

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +  font-size: 14px;
унеси fz: 14 и line-height: 130% в body и не повторяй в каждом теге. Переиспользуй стили

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +.goOver {
что такое goOver?

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +.block {
плохое имя для класса. Называй по смыслу элемента

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.tsx
> +function Clock() {
функция это действие - значит и называться она должна с глагола. Тут подойдет get. А полностью можно назвать getFormatedDate.

Подробнее про именование: https://habr.com/ru/post/488378/

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.tsx
> +function Year() {
отредактируй название функции

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.tsx
> +  });
у useEffect должен быть второй аргумент

2022-05-02 21:18 UTC, chervyakovru commented on src/Footer/Footer.tsx
> +              {
зачем тут скобка?

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Main.module.css
> +  display: flex;
тут не нужен flex

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Main.module.css
> +  vertical-align: middle;
vertical-align тут бесполезен

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Main.module.css
> +  box-shadow: rgb(72 72 72 / 30%) 0px 0.5px 0px;
не надо так. Слишком сложно. Тень стоит использовать для тени. Если тебе просто нужна линия сделай border

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Main.module.css
> +  font-weight: 400;
не надо писать font-weight: 400; для тегов которые не перопределяют базовые стили шрифта body

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Main.module.css
> +  margin: auto 0;
лучше воспользоваться align-items: center у родителя. Так более предсказуемо

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Main.module.css
> +  font-weight: 400;
не надо писать font-weight: 400; для тегов которые не перопределяют базовые стили шрифта body

2022-05-02 21:18 UTC, chervyakovru commented on src/index.css
> +  font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
ты загружаешь шрифт NeueMachina но не используешь его. Это странно

2022-05-02 21:18 UTC, chervyakovru commented on src/Slider/Slider.module.css
> +@keyframes circle {
Нужно будет поработать с анимацией. Но в конце

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Portfolio/Portfolio.tsx
> +            <div className={styles.img}></div>
так задавать картинки не класно. Пусть картинки будут картинками почему нет?

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Portfolio/Portfolio.module.css
> +  width: 530px;
Зачем задавать фиксированную ширину если можно отталкиваться от картинки?

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Portfolio/Portfolio.module.css
> +  height: 287px;
не нужно дублировать значения в стилях. Если есть необходимость на несколько элементов накинуть стили сделай отдельный класс

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Portfolio/Portfolio.module.css
> +  width: 1600px;
у top_circle и .bottom_circle одинаковые стили кроме анимации. Выдели общии в отельный класс

2022-05-02 21:18 UTC, chervyakovru commented on src/Main/Main.tsx
> +          <div className={styles.row}>
Лучше сделать весь блок ссылкой. Так будет удобнее нажимать

2022-05-07 15:31 UTC, Poldyaich97 commented on src/Main/Portfolio/Portfolio.module.css
> +  width: 1600px;
Мы убрали анимацию. Смысла нет

2022-05-07 15:32 UTC, Poldyaich97 commented on src/Main/Portfolio/Portfolio.module.css
> +  height: 287px;
исправлено

2022-05-07 15:32 UTC, Poldyaich97 commented on src/Main/Portfolio/Portfolio.module.css
> +  width: 530px;
уже

2022-05-07 15:33 UTC, Poldyaich97 commented on src/Slider/Slider.module.css
> +@keyframes circle {
А что с ней?

2022-05-07 15:37 UTC, Poldyaich97 commented on src/index.css
> +  font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
исправил

2022-05-07 15:41 UTC, Poldyaich97 commented on src/Main/Main.module.css
> +  margin: auto 0;
+

2022-05-07 15:42 UTC, Poldyaich97 commented on src/Main/Main.module.css
> +  font-weight: 400;
+

2022-05-07 15:42 UTC, Poldyaich97 commented on src/Main/Main.module.css
> +  vertical-align: middle;
+

2022-05-07 15:43 UTC, Poldyaich97 commented on src/Main/Main.module.css
> +  display: flex;
+

2022-05-07 15:44 UTC, Poldyaich97 commented on src/Footer/Footer.tsx
> +              {
ошибка

2022-05-07 15:44 UTC, Poldyaich97 commented on src/Footer/Footer.tsx
> +  });
уже обусдили

2022-05-07 15:44 UTC, Poldyaich97 commented on src/Footer/Footer.tsx
> +function Year() {
+

2022-05-07 15:44 UTC, Poldyaich97 commented on src/Footer/Footer.tsx
> +function Clock() {
+

2022-05-07 15:50 UTC, Poldyaich97 commented on src/Footer/Footer.module.css
> +.block {
+

2022-05-07 15:52 UTC, Poldyaich97 commented on src/Footer/Footer.module.css
> +.goOver {
изменил на link

2022-05-07 15:52 UTC, Poldyaich97 commented on src/Footer/Footer.module.css
> +  font-size: 14px;
+

2022-05-07 15:55 UTC, Poldyaich97 commented on src/Footer/Footer.module.css
> +  border: 1px solid #ffffff;
+

2022-05-07 15:55 UTC, Poldyaich97 commented on src/Footer/Footer.module.css
> +  border: 0.2px solid #ffffff;
+

2022-05-07 15:56 UTC, Poldyaich97 commented on src/Footer/Footer.module.css
> +  display: flex;
+

2022-05-10 18:42 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/167699802-3aca7b7d-77c7-40f1-87fc-cbf08595b7ef.png)

2022-05-10 18:45 UTC, chervyakovru commented
А чего Frontend developer не по кругу гоняет?

2022-05-10 18:47 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/167700510-5ec22b4b-9d02-4d62-8b24-f3265d2b27d6.png)

2022-05-10 18:47 UTC, chervyakovru commented
![Uploading image.png…]()

2022-05-10 18:48 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/167700686-355a5ada-f25e-432f-91d8-6f2d33ad6af7.png)

2022-05-10 19:18 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/167705322-42be5796-78e8-48ed-bc7a-66b82ed697bd.png)
Размер картинки в стилях не нужно задавать. Его нужно или не задавать, или задавать в процентах или писать в атрибутах

2022-05-10 19:33 UTC, chervyakovru commented on src/index.css
> +  font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
тут нужно оставить пару фонтов на фолбек. Иначе, если не загрузится твой шрифт, то будет вот так
![image](https://user-images.githubusercontent.com/14909082/167707862-50d9792c-e602-419b-8503-18f7f75a3b0d.png)

2022-05-10 19:34 UTC, chervyakovru commented on src/Slider/Slider.module.css
> +@keyframes circle {
не по кругу

2022-05-10 19:39 UTC, chervyakovru commented
![image](https://user-images.githubusercontent.com/14909082/167708662-f4b34871-a0a2-48ad-8eb4-78783c2c6eaf.png)
Что такое circle? никаого круга не увидел на макете
почему фиксированная ширина? Почему 1600? Зачем margin 0? Зачем вообще этот тег, если есть row

2022-05-10 19:41 UTC, chervyakovru commented on src/Footer/Footer.module.css
> +  font-size: 14px;
Не везде поправил
![image](https://user-images.githubusercontent.com/14909082/167709144-8fc2793f-ccba-4b2e-8c57-532ff726ac64.png)

2022-05-10 19:42 UTC, chervyakovru commented on src/Main/Portfolio/Portfolio.module.css
> +  width: 530px;
че то там все равно не то

2022-05-20 05:46 UTC, Poldyaich97 commented on src/Main/Portfolio/Portfolio.module.css
> +  width: 530px;
Убрал размеры картинки. 
Ширина карточек задается падингами

2022-05-30 13:39 UTC, merged